// Client-side error reporter for the `client_errors` Supabase table.
//
// Design constraints:
//   1. Redact before insert. No JWTs, no base32 seeds, no bytea literals,
//      no email addresses ever hit the table. We mirror the server-log
//      redaction list so both edges are consistent.
//   2. Silent-fail. If Supabase is unavailable, the app must not itself
//      throw a second error because we tried to report the first one.
//   3. Cheap. Cap at 20 inserts per session-minute so a runaway render
//      loop doesn't fill the table.
//
// See `supabase/migrations/20260706100100_client_errors.sql` for the
// destination schema. RLS accepts INSERT from `anon` (user_id null) and
// from `authenticated` (user_id = auth.uid()); SELECT is admin-only.

import { supabase } from "@/integrations/supabase/client";

const REDACT_PATTERNS: [RegExp, string][] = [
  [/eyJ[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]{5,}/g, "[REDACTED_JWT]"],
  [/sb_(?:secret|publishable)_[a-zA-Z0-9]{20,}/g, "[REDACTED_SB_KEY]"],
  [/[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/g, "[REDACTED_EMAIL]"],
  [/\b[A-Z2-7]{20,}={0,2}\b/g, "[REDACTED_BASE32]"],
  [/\\x[0-9a-fA-F]{16,}/g, "[REDACTED_BYTEA]"],
];

function redact(input: string): string {
  let out = input;
  for (const [re, rep] of REDACT_PATTERNS) out = out.replace(re, rep);
  return out;
}

// In-tab burst limiter. 20 rows / 60s / tab.
const BUCKET_LIMIT = 20;
const BUCKET_WINDOW_MS = 60_000;
const bucket: number[] = [];

function shouldEmit(now: number): boolean {
  while (bucket.length > 0 && bucket[0] <= now - BUCKET_WINDOW_MS) bucket.shift();
  if (bucket.length >= BUCKET_LIMIT) return false;
  bucket.push(now);
  return true;
}

// Import from generated types module lazily to avoid pulling more of the
// Supabase types graph than we need at module init.
export interface ClientErrorReport {
  message: string;
  stack?: string;
  route?: string;
  extra?: Record<string, unknown>;
}

const BUILD_SHA =
  (typeof import.meta !== "undefined" && (import.meta as { env?: { VITE_BUILD_SHA?: string } }).env?.VITE_BUILD_SHA) ||
  undefined;

// Public API. Never rejects — errors from the reporter itself are
// swallowed so callers can `await reportClientError(...)` inside a
// catch block without worrying about a secondary throw.
export async function reportClientError(input: ClientErrorReport | unknown): Promise<void> {
  try {
    const report: ClientErrorReport =
      input && typeof input === "object" && "message" in (input as ClientErrorReport)
        ? (input as ClientErrorReport)
        : normalize(input);

    if (!shouldEmit(Date.now())) return;

    const message = redact(String(report.message ?? "unknown")).slice(0, 2000);
    const stack = report.stack ? redact(report.stack).slice(0, 8000) : null;
    const route =
      report.route ??
      (typeof window !== "undefined" ? window.location.pathname : null);
    const user_agent =
      typeof navigator !== "undefined" ? navigator.userAgent.slice(0, 500) : null;

    const { data: userData } = await supabase.auth.getUser();
    const user_id = userData?.user?.id ?? null;

    // types.ts is autogenerated from Supabase and doesn't yet know about
    // the client_errors table (added in migration 20260706100100). Cast
    // so we don't fight the generator; it will regenerate on the next
    // `supabase db push`.
    await (supabase as unknown as {
      from: (table: string) => { insert: (row: Record<string, unknown>) => Promise<unknown> };
    })
      .from("client_errors")
      .insert({
        user_id,
        message,
        stack_redacted: stack,
        route: route?.slice(0, 500) ?? null,
        user_agent,
        build_sha: BUILD_SHA ?? null,
        vault_crypto_version: 1,
      });
  } catch {
    /* silent — reporter must never itself throw */
  }
}

function normalize(err: unknown): ClientErrorReport {
  if (err instanceof Error) {
    return { message: err.message, stack: err.stack };
  }
  try {
    return { message: JSON.stringify(err) };
  } catch {
    return { message: String(err) };
  }
}

// Auto-hook global error events once per tab. Import-side-effect only.
if (typeof window !== "undefined") {
  window.addEventListener("error", (event) => {
    void reportClientError({
      message: event.message,
      stack: (event.error as Error | undefined)?.stack,
      route: window.location.pathname,
      extra: { source: "window.onerror", line: event.lineno, col: event.colno },
    });
  });
  window.addEventListener("unhandledrejection", (event) => {
    const r = event.reason;
    void reportClientError({
      message: r instanceof Error ? r.message : String(r),
      stack: r instanceof Error ? r.stack : undefined,
      route: window.location.pathname,
      extra: { source: "unhandledrejection" },
    });
  });
}
